package com.food.dao;

import com.food.pojo.BlackList;

public interface BlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated
     */
    int insert(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated
     */
    int insertSelective(BlackList record);
}