package com.food.dao;

import com.food.pojo.Focus;

public interface FocusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int insert(Focus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table focus
     *
     * @mbggenerated
     */
    int insertSelective(Focus record);
}