package com.food.dao;

import java.util.List;

import com.food.pojo.Party;

public interface PartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int insert(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int insertSelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    Party selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Party record);
    
    public List<Party> selectAll();
}