package com.food.dao;

import com.food.pojo.PartyUser;

public interface PartyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partyuser
     *
     * @mbggenerated
     */
    int insert(PartyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partyuser
     *
     * @mbggenerated
     */
    int insertSelective(PartyUser record);
}