package com.food.pojo;

import java.io.Serializable;

public class HomePage implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homepage.hid
     *
     * @mbggenerated
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homepage.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homepage.htype
     *
     * @mbggenerated
     */
    private String htype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homepage.hid
     *
     * @return the value of homepage.hid
     *
     * @mbggenerated
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homepage.hid
     *
     * @param hid the value for homepage.hid
     *
     * @mbggenerated
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homepage.pid
     *
     * @return the value of homepage.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homepage.pid
     *
     * @param pid the value for homepage.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homepage.htype
     *
     * @return the value of homepage.htype
     *
     * @mbggenerated
     */
    public String getHtype() {
        return htype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homepage.htype
     *
     * @param htype the value for homepage.htype
     *
     * @mbggenerated
     */
    public void setHtype(String htype) {
        this.htype = htype == null ? null : htype.trim();
    }
}