package com.food.pojo;

import java.io.Serializable;
import java.util.Date;

public class Party implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.pmoney
     *
     * @mbggenerated
     */
    private Double pmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.pnumber
     *
     * @mbggenerated
     */
    private Integer pnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.partyTime
     *
     * @mbggenerated
     */
    private Date partytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.pImg
     *
     * @mbggenerated
     */
    private String pimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column party.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.pid
     *
     * @return the value of party.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.pid
     *
     * @param pid the value for party.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.uid
     *
     * @return the value of party.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.uid
     *
     * @param uid the value for party.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.pname
     *
     * @return the value of party.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.pname
     *
     * @param pname the value for party.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.pmoney
     *
     * @return the value of party.pmoney
     *
     * @mbggenerated
     */
    public Double getPmoney() {
        return pmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.pmoney
     *
     * @param pmoney the value for party.pmoney
     *
     * @mbggenerated
     */
    public void setPmoney(Double pmoney) {
        this.pmoney = pmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.pnumber
     *
     * @return the value of party.pnumber
     *
     * @mbggenerated
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.pnumber
     *
     * @param pnumber the value for party.pnumber
     *
     * @mbggenerated
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.partyTime
     *
     * @return the value of party.partyTime
     *
     * @mbggenerated
     */
    public Date getPartytime() {
        return partytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.partyTime
     *
     * @param partytime the value for party.partyTime
     *
     * @mbggenerated
     */
    public void setPartytime(Date partytime) {
        this.partytime = partytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.endTime
     *
     * @return the value of party.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.endTime
     *
     * @param endtime the value for party.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.pImg
     *
     * @return the value of party.pImg
     *
     * @mbggenerated
     */
    public String getPimg() {
        return pimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.pImg
     *
     * @param pimg the value for party.pImg
     *
     * @mbggenerated
     */
    public void setPimg(String pimg) {
        this.pimg = pimg == null ? null : pimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.tag
     *
     * @return the value of party.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.tag
     *
     * @param tag the value for party.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.type
     *
     * @return the value of party.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.type
     *
     * @param type the value for party.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.province
     *
     * @return the value of party.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.province
     *
     * @param province the value for party.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.city
     *
     * @return the value of party.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.city
     *
     * @param city the value for party.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.area
     *
     * @return the value of party.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.area
     *
     * @param area the value for party.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }
}