package com.food.pojo;

import java.io.Serializable;

public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbggenerated
     */
    private String uemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.headPortrait
     *
     * @mbggenerated
     */
    private String headportrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uprovince
     *
     * @mbggenerated
     */
    private String uprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ucity
     *
     * @mbggenerated
     */
    private String ucity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uarea
     *
     * @mbggenerated
     */
    private String uarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbggenerated
     */
    public String getUemail() {
        return uemail;
    }
    
    public User(){}

    public User(Integer uid, String uemail, String uname, String password, String headportrait, String sex, String tel,
			String uprovince, String ucity, String uarea, String intro) {
		super();
		this.uid = uid;
		this.uemail = uemail;
		this.uname = uname;
		this.password = password;
		this.headportrait = headportrait;
		this.sex = sex;
		this.tel = tel;
		this.uprovince = uprovince;
		this.ucity = ucity;
		this.uarea = uarea;
		this.intro = intro;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbggenerated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.headPortrait
     *
     * @return the value of user.headPortrait
     *
     * @mbggenerated
     */
    public String getHeadportrait() {
        return headportrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.headPortrait
     *
     * @param headportrait the value for user.headPortrait
     *
     * @mbggenerated
     */
    public void setHeadportrait(String headportrait) {
        this.headportrait = headportrait == null ? null : headportrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uprovince
     *
     * @return the value of user.uprovince
     *
     * @mbggenerated
     */
    public String getUprovince() {
        return uprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uprovince
     *
     * @param uprovince the value for user.uprovince
     *
     * @mbggenerated
     */
    public void setUprovince(String uprovince) {
        this.uprovince = uprovince == null ? null : uprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ucity
     *
     * @return the value of user.ucity
     *
     * @mbggenerated
     */
    public String getUcity() {
        return ucity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ucity
     *
     * @param ucity the value for user.ucity
     *
     * @mbggenerated
     */
    public void setUcity(String ucity) {
        this.ucity = ucity == null ? null : ucity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uarea
     *
     * @return the value of user.uarea
     *
     * @mbggenerated
     */
    public String getUarea() {
        return uarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uarea
     *
     * @param uarea the value for user.uarea
     *
     * @mbggenerated
     */
    public void setUarea(String uarea) {
        this.uarea = uarea == null ? null : uarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.intro
     *
     * @return the value of user.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.intro
     *
     * @param intro the value for user.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}