package com.food.pojo;

import java.io.Serializable;

public class Focus implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column focus.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column focus.fid
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column focus.uid
     *
     * @return the value of focus.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column focus.uid
     *
     * @param uid the value for focus.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column focus.fid
     *
     * @return the value of focus.fid
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column focus.fid
     *
     * @param fid the value for focus.fid
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}