package com.food.dao;

import com.food.pojo.HomePage;

public interface HomePageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homepage
     *
     * @mbggenerated
     */
    int insert(HomePage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homepage
     *
     * @mbggenerated
     */
    int insertSelective(HomePage record);
}