package com.food.dao;

import com.food.pojo.Messages;

public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbggenerated
     */
    int insertSelective(Messages record);
}